'use client';

import FileDownloadIcon from '@mui/icons-material/FileDownload';
import { Button, Stack } from '@mui/material';
import { AppChip } from '../../../../components/common/AppChip';
import { CompactDataTable } from '../../../../components/common/CompactDataTable';
import { SectionPanel as Section } from '../../../../components/common/WorkspacePrimitives';
import { ReportExportRow, ReportsOverview } from './report-types';
import { arrayValue, formatDate, stringValue } from './report-utils';

export function ReportJourneyTab({
  reportsOverview,
  reportExportRows,
  downloadReportFile
}: {
  reportsOverview: ReportsOverview;
  reportExportRows: ReportExportRow[];
  downloadReportFile: (fileId: string, fileName: string) => void;
}) {
  return (
    <Stack spacing={0.85}>
      <Section title="Generated Report History" defaultExpanded={false}>
        <CompactDataTable
          columns={['File', 'Type', 'Status', 'Rows', 'Generated By', 'Requested', 'Action']}
          rows={reportExportRows.map((row) => [
            row.fileName ?? '-',
            row.reportType ?? '-',
            <AppChip key={`${row.id}-status`} label={row.status ?? 'completed'} />,
            String(row.rowCount ?? 0),
            row.requestedByName ?? '-',
            formatDate(row.requestedAt ?? row.createdAt),
            row.fileId ? <Button key={`${row.id}-download`} size="small" startIcon={<FileDownloadIcon />} onClick={() => downloadReportFile(row.fileId ?? row.id, row.fileName ?? 'unnatify-report.csv')}>Download</Button> : '-'
          ])}
        />
      </Section>
      <Section title="Conversion and Expired Leads" defaultExpanded={false}>
        <CompactDataTable
          columns={['Lead', 'Mobile', 'Status', 'Category', 'Expiry', 'Updated']}
          rows={(reportsOverview.expiredLeads ?? []).map((lead) => [
            stringValue(lead.customerName),
            stringValue(lead.mobile),
            <AppChip key={`${stringValue(lead.id)}-status`} label={stringValue(lead.status)} />,
            stringValue(lead.category),
            formatDate(stringValue(lead.offerExpiryDate)),
            formatDate(stringValue(lead.updatedAt))
          ])}
        />
      </Section>
      <Section title="Full Customer Journey" defaultExpanded={false}>
        <CompactDataTable
          columns={['Lead', 'Mobile', 'Status', 'Activities', 'Tasks', 'Updated']}
          rows={(reportsOverview.recentLeadJourneys ?? []).map((lead) => [
            stringValue(lead.customerName),
            stringValue(lead.mobile),
            <AppChip key={`${stringValue(lead.id)}-status`} label={stringValue(lead.status)} />,
            String(arrayValue(lead.activities).length),
            String(arrayValue(lead.tasks).length),
            formatDate(stringValue(lead.updatedAt))
          ])}
        />
      </Section>
    </Stack>
  );
}
